### ISSUE TITLE
FacetSpec.Prefix

### ISSUE THREAD

**Issue by dtosato** [NightOwl888/BoboBrowse.Net#1]
Hi all, `FacetSpec.Prefix` has been removed from the 3.2.0. So, it is impossible to write something like that:
```c#
FacetSpec spec = new FacetSpec();
spec.Prefix = "xxx"; 
```
Is that correct?

**Comment by NightOwl888** [comment]
Thanks for the report.

I don't know the exact reasoning behind this change, but I can tell you that the prefix setter and getter for this field were already removed in BoboBrowse 2.1.0 in the Java version (in about mid-2009). I couldn't find the exact commit where they were removed, though.

I also tried to find an issue on [Google Code](https://code.google.com/p/bobo-browse/issues/list?can=1&q=&colspec=ID+Type+Status+Priority+Milestone+Owner+Summary&cells=tiles) and on [SourceForge](http://sourceforge.net/p/bobo-browse/bugs/search/?q=%21status%3Awont-fix+%26%26+%21status%3Aclosed-fixed+%26%26+%21status%3Aclosed) regarding this, but there doesn't seem to be any information as to what the reasoning behind this change was.

My best guess is that this was seen as duplicate functionality because you can use a FacetFilter to do essentially the same thing. However, there are no built-in FacetFilters that filter by prefix, so once again I am stumped.

It is possible now to add your own properties to the Properties dictionary to pass through the process, but they aren't used as filters internally like the Filter property was previously.

A way that you can potentially add this back in is to override GetFacetCountCollector on the facet handler you are interested in and replace it with a custom class that inherits DefaultFacetCountCollector and overrides [GetFacets](https://github.com/NightOwl888/BoboBrowse.Net/blob/master/src/BoboBrowse.Net/BoboBrowse.Net/Facets/Impl/DefaultFacetCountCollector.cs#L124), substituting the implementation from the [2.x version of DefaultFacetCountCollector.GetFacets](https://github.com/NightOwl888/BoboBrowse.Net/blob/e515ed82753feaf4250289c06aa64432f17ceec5/src/BoboBrowse.Net/Facets/Impl/DefaultFacetCountCollector.cs#L100). You can use the Properties dictionary to add the value you want to filter to the FacetSpec object.

**Comment by NightOwl888** [comment]
Closing this as a wont fix because it is not part of the Java version.
