### ISSUE TITLE
BrowseFacet for ranges

### ISSUE THREAD

**Issue by dtosato** [NightOwl888/BoboBrowse.Net#10]
@NightOwl888 
Hi, I do not understand why `BrowseFacet` has not a specialized version for ranges that replaces
```c#
public virtual string Value { get; set; }
```
with
```c#
public virtual string UpperBoundValue{ get; set; }
public virtual string LowerBoundValue{ get; set; }
```
It would be much easier to manage the formatting problem with this solution. Moreover, it seems to me that to compose the range string values (e.g. [a TO b]) is quite time consuming.
Do you agree?

**Comment by NightOwl888** [comment]
Actually, there is a [RangeFacet](https://github.com/NightOwl888/BoboBrowse.Net/blob/master/src/BoboBrowse.Net/BoboBrowse.Net/Facets/Impl/RangeFacetCountCollector.cs#L367) that works much like you described, but it is a private type. There is really no way to expose this functionality to the outside without an explicit cast. But also, it is an *input*. The facets that are generated at the output are done so at a level deep in the API (in the RangeFacetCountCollector and then again in the CombinedFacetCountCollector), not in the FacetHandler, and at that point there is no straightforward way to specify the type of BrowseFacet to generate (it applies to all of the facet handlers). The only thing tying the input to the output is the range string.

I also considered making a tool to manage the strings in a similar way, but it seemed like it would be even more difficult to understand and manage, especially when you consider that you would need to regenerate the strings on each round trip the same way that they are done at application startup. So it would need some way to match the output of the BrowseFacet up with a type that is pre-configured to be the same as the FacetHandler. Technically, the BoboIndexReader is supposed to be configured as a singleton (once during application startup), so that would make it necessary to somehow regenerate the same configuration at startup and on each round trip (or also make this configuration into a singleton).

When you consider *how* the strings are used, creating a unified tool like that is not straightforward.

1. The RangeFacetHandler inputs are (normally) generated at application startup. This can be done through Spring.NET XML configuration.
2. The BrowseFacet instances (for output) are generated deep within the API (in the RangeFacetCountCollector and CombinedFacetCountCollector) on each round trip. Only the facet values that match the current query are output unless FacetSpec.ExpandSelection is specified.
3. The BrowseSelections correspond to what the user selected on the API, and must exactly match the format specified in the RangeFacetHandler. This is problematic when you consider that the string that is displayed to the user may be formatted in a specific culture, so matching it upon return trip from the UI is a challenge.
4. RangeFacetHandler could potentially also be used as a runtime facet handler by calling BoboBrowser.SetFacetHandler to make dynamic ranges.

So, the primary factor to consider is where in the application lifecycle the configuration of the range facet generator would be stored so it could be used to generate the input strings, generate the output format strings for the UI, and then be matched on round trip from the UI again so it could produce the original strings for the BrowseSelections. In the end, it seemed more straightforward to generate a throw away user-friendly culture-specific range string at the end of each browse request than to try to work out a storage and matching mechanism for the range generator objects that could be used at each of the places in the application lifecycle. And leave it up to the UI to store the actual range string for the round trip.

That said, I agree with you that it *should* be simpler. There are a lot of design decisions that were made on this project that I personally don't agree with, especially when it comes to data types and dependency injection. But, it is much less time consuming to make a port of an existing design than to come up with a design of my own. Staying true to the original design means that the existing intentions of the application's usage are preserved and I believe it is the best course of action to make this project maintainable over time, even if I don't personally agree with all of the choices.

That said, this design is somewhat extensible. If you would like to contribute a *new* RangeFacetHandler that works more to your liking, I would be happy to wrap it up into a new NuGet package (something like BoboBrowse.Net.Extensions) so it can be downloaded as an add-on to this package. Perhaps there is a way to internalize all of the data necessary to make it work (including type info) into the range strings, and then make an extension method for BrowseFacet that can convert those strings into the formatted strings, or better yet, convert it into a RangeBrowseFacet instance. This doesn't get around the fact that the string will need to be the same on the round trip from the UI, but if the type info is embedded in the string it won't have to be supplied explicitly, nor will you need to instantiate an external tool to get the formatted string for the UI.

**Comment by NightOwl888** [comment]
I am closing this as a wontfix for now. Feel free to reopen this issue if you decide you want to contribute a custom RangeFacetHandler that meets these goals.
