### ISSUE TITLE
3.2.0 stability

### ISSUE THREAD

**Issue by dtosato** [NightOwl888/BoboBrowse.Net#2]
Hi all, which is the stability of this porting of Bobo? Do you plan to release the 3.2.0?

**Comment by NightOwl888** [comment]
Yes, 3.2.0 is the version that is most stable and will be released when I have determined that there are no significant issues (such as performance problems or memory leaks). 

Your analysis will probably be given considerable weight in that regard since there doesn't seem to be much interest so far. But then, this repo hasn't been indexed by Google yet.

I haven't tested every aspect of it, but I have run some tests on a prototype that I made as well as the CarDemo application and all seems well so far. In addition, all unit tests that were ported are passing. Unfortunately, there are some performance tests that I am unable to port because they have dependencies to files that were not checked into the repository, and my efforts to obtain them by contacting John Wang directly didn't pan out.
