### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by Jogai** [NightOwl888/BoboBrowse.Net#34]
> Alpha - awaiting port of StandardAnalyzer and QueryParser of Lucene.Net 4.8.0, as well as releases for .NET 3.5 and 4.0.

I think  StandardAnalyzer and QueryParser of Lucene.Net 4.8.0 are fine now in the latest 4.8 beta package. This might be alpha, but probably not for that reason

**Comment by NightOwl888** [comment]
Correct, `StandardAnalyzer` and `QueryParser` were ported some time ago. However, I also discovered while working on Lucene.Net that [bobo-browse never progressed past 4.0.2](https://github.com/senseidb/bobo/releases) because it has been superseded by the facet functionality of Lucene 4.0 (available in .NET as [Lucene.Net.Facet](https://www.nuget.org/packages/Lucene.Net.Facet/4.8.0-beta00006)).

While there *could* be a BoboBrowse.Net 4.0.2, it is unlikely that there will be a version after that. Lucene.Net will eventually move on and there won't be a BoboBrowse.Net that supports the latest version anymore. There are also some bug fixes that were committed to bobo-browse that were never released in Java that *could* be released in .NET. But whether there will be a BoboBrowse.Net 4.0.2 will depend on demand, and so far you are the first who has asked for it.

While I don't have an issue with completing the port, keep in mind that there will never be a version higher than 4.0.2. Eventually Lucene.Net will move on to a higher version that is incompatible with BoboBrowse.Net. Since in the Java world bobo-browse has been superseded by the facet package of lucene, I would recommend following the same upgrade path.

**Comment by Jogai** [comment]
Thanks for your answer. I was already trying with the facets, but didnt get it to work yet. But its good to know that bobobrowse is superseeded, at least I know I have to try harder...
