### ISSUE TITLE
TermValueListFactory<T>

### ISSUE THREAD

**Issue by dtosato** [NightOwl888/BoboBrowse.Net#6]
The [documentation](https://github.com/NightOwl888/BoboBrowse.Net/wiki/Prebuilt-Facet-Handler-Types) shows the usage of  `TermValueListFactory<T>`. Apparently, this generic class does not exist, so which is the right class to implement  the examples of the **Range Strings** section? 
I tried to use the `PredefinedTermListFactory<T>`, but it does not work as you wrote.
Could you show me an actual example to manage string ranges?
Thanks.

**Comment by NightOwl888** [comment]
Could this be another issue due to the fact that you didn't have the latest version? [`PredefinedTermListFactory<TSupported>`](https://github.com/NightOwl888/BoboBrowse.Net/blob/master/src/BoboBrowse.Net/BoboBrowse.Net/Facets/Data/PredefinedTermListFactory.cs#L24) definitely does exist.

The `TermStringList` is the default when no `TermValueListFactory<T>` is supplied. So, if you either pass null or call an overload that does not accept a `termListFactory` argument, you will have a RangeFacetHandler that works with strings.

var stringFacetHandler = new RangeFacetHandler("name", new string[] { "[a TO d)", "[d TO g)", "[g TO j)" });

The only example I can think of where a string makes sense for a range facet is for some kind of dictionary or glossary where you want to lookup words based on a range of letters or words that begin with specific letters. Of course, for it to work as expected, you may need to build a custom sort that takes into consideration [natural sort order](http://blog.codinghorror.com/sorting-for-humans-natural-sort-order/) for text.

**Comment by NightOwl888** [comment]
As you pointed out, there was a problem with the documentation which has now been addressed.
